### ISSUE TITLE
Limit on Number of Scripts

### ISSUE THREAD

**Issue by SuperGoomba** [aanbarasan/website-scripting#4]
There appears to be a limit on the number of scripts you can save. I currently have 45 scripts saved in Chrome, but whenever I try and save another, the extension tells me that the script was saved, but it does not appear in the list of extensions and doesn't execute when I load the relevant page. As I can find no information suggesting that it's intentional that there is a limit (and, again, it does actually tell me that a script was saved when I try and save an additional script), I'm inclined to assume this is a bug.

(As a note -- I'm not sure, but I suspect that the limit has more to do with the size of the scripts than the exact number. This is because I originally seemed to have reached the limit at 39 scripts, but was able to save more after deleting all the sample scripts that come with the extension; the scripts I have been writing are all much smaller than any of the sample ones were).

**Comment by aanbarasan** [comment]
Hi, @SuperGoomba thanks for reaching out. I can see there is a bug while confirming the data is saved or not. And there is a space limit I guess. Will take that into action and update you shortly.

**Comment by aanbarasan** [comment]
This issue is fixed in the latest version of extension version 2.7.5
